version : '3.7'
networks:
  redis-net:
    external: true
services:
  redis:
        container_name : trsredis5.0
        hostname: trsredis5.0
        restart: on-failure
        networks:
          redis-net:
        image: registry.cn-hangzhou.aliyuncs.com/yangyuanpeng/redis:5.05-diy
        volumes:
           - /redis/data:/var/lib/redis
           - /redis/log:/var/log/redis
           - /redis/conf:/usr/local/etc/redis
        ports :
          - 6379:6379

